repos:
  - repo: local
    hooks:
      - id: custom-formatter
        name: Custom Python Formatter
        entry: python scripts/formatter.py
        language: system
        types: [ python ]
      - id: custom-linter
        name: Custom Python Linter
        entry: python scripts/linter.py
        language: system
        types: [ python ]
